### ISSUE TITLE
neo.ahk 配套键位图问题

### ISSUE THREAD

**Issue by Tyrone2333** [district10/neo_keyboard_layout#1]
neo_keyboard_layout/neo4win/neo.ahk 这里面的ahk是哪一种布局？ ' [ ] 这三个没有变，既不是dvpe0.3 也不是 Extended Programmer Dvorak ，能不能在目录里配一张键位图

**Comment by district10** [comment]
谢谢回复哈。因为懒，没有更新键位图。用了一段时间的 Programmer Dvorak 后觉得太丧心病狂了。所以现在 neo 键盘布局只改了字母区。数字和括弧等符号没有调整。（不过 Level 3 有针对写代码把 `()[]{}` 提取到字母区域，具体见代码：<https://github.com/district10/neo_keyboard_layout/blob/6f5a6e325c2f174dccec143c3717023a4d10a946/neo4win/neo.ahk#L46-L69>）

布局图：

Level1:

![level1](https://user-images.githubusercontent.com/5262037/28498862-a22772fa-6fc5-11e7-92aa-d947721d325c.png)

Level2:

![level2](https://user-images.githubusercontent.com/5262037/28498816-75f887d8-6fc4-11e7-9cdf-09fe439f7b2a.png)

Level3:

按住空格键来输入。比如空格键+o（QWERTY 上的 s）为方向键左。
这个暂时没有图……

**Comment by district10** [comment]
外，入坑需谨慎哈。我这个修改过的版本给自己造成了不少麻烦（但是因为我适应了，所以我只能自己慢慢克服）。用标准的 Dvorak 的话会省事儿很多，毕竟系统可能自带了。

**Comment by Tyrone2333** [comment]
`space & o::Send {(} `不是输出（吗，怎么变左了
 。。括号经常用的弄这麻烦，wiki有个程序员版的dvorak，结合改造嘿嘿

**Comment by district10** [comment]
因为那个 o 说的是 QWERTY 键位上的 o。“空格键+o（QWERTY 上的 s）为方向键左” 对应代码为：`space & s::Send {Left}`。

**Comment by Tyrone2333** [comment]
如果是要把数字4改成$，shift + 4 改成4 ，要怎么写？不懂这个语法`shift & 4::Send {$}` 它报错

**Comment by district10** [comment]
文档在这里：https://autohotkey.com/docs/Hotkeys.htm 

这里有一个现成的：https://autohotkey.com/board/topic/102725-problem-making-the-number-row-map-to-programmer-dvorak/

**Comment by Tyrone2333** [comment]
我昨天被那个%的转义搞了一晚上，现在解决了。但是我发现一个问题，我用的QQ输入法把数字和符号替换后选字的时候按2出来的是@，用shift+数字键不能实现候选字的输入会直接输出一个数字，qq输入法没有自定义选字的功能只能暂时用右边遥远的小数字来选择，请问你是怎么弄的？ 我在google也没能找到解决方案。

**Comment by district10** [comment]
我想这个输入法的 bug 不是那么好处理……因为我没有用 Programmer Dvorak 所以我也不太清楚。
